name: Build

on: [workflow_dispatch]

#See latest SDK: https://wiki.teltonika-networks.com/view/Software_Development_Kit
env:
  VERSION: "RUTX_R_GPL_00.07.02.2.tar.gz"

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 150

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          docker build \
            --pull \
            --build-arg RUTOS_VERSION=$VERSION \
            -t ghcr.io/paresy/rutx-sdk:$VERSION \
            -f Dockerfile .

      - name: Push
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/paresy/rutx-sdk:$VERSION